### PR TITLE
Adding encoding aided by the JSON ABI

### PR DESCRIPTION
**Pull request by pouladzade**
1-Adding encoding aided by the JSON ABI (` encode(json_abi, function_name, parameter_list)` )
2- Updating the readme
3- Adding tests regarding the new encoding method

**Example**:
```js
var json_abi = [{"constant":false,"inputs":[{"name":"a","type":"int256"}],"name":"setA","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"a","type":"int256"},{"name":"b","type":"string"},{"name":"c","type":"bytes8"}],"name":"setABC","outputs":[{"name":"","type":"int256"},{"name":"","type":"string"},{"name":"","type":"bytes8"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"b","type":"string"}],"name":"setB","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"c","type":"bytes8"}],"name":"setC","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"}]

var encoded = abi.encode(json_abi, 'setABC', [12, 'salam', [1, 2, 3, 4, 5, 6, 7, 8]])
console.log(encoded.toString("hex"))
```
Output:
```js
f77a13e1000000000000000000000000000000000000000000000000000000000000000c00000000000000000000000000000000000000000000000000000000000000600102030405060708000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000573616c616d000000000000000000000000000000000000000000000000000000
```

### CODE REVIEW

**Comment by holgerd77** [comment]
Hi @pouladzade, thanks, great that you are tackling this! 😄

Is this ready for review?

**Comment by pouladzade** [comment]
Hi @holgerd77 ,
You are welcome!
Yes, I would be happy if you review the codes and let me know if I need to change it.

**Comment by holgerd77** [comment]
Hi Ahmad, sorry didn't find the time. I understand if you loose patience, but would also be a pity if all the work gets lost. If you would be willing to reopen I'll try to more quickly address.

**Comment by pouladzade** [comment]
Hi @holgerd77 
Thank you so much for your kind comment.
I have implemented the decode method as well,  but I need to test it more and make sure that I have considered all the corner cases, then I will open a new pr for sure.
I am providing encode and decode using JSON ABI for both Input and output parameters.

**Pull request closed without merging**
