### PR TITLE
Bump major version of ethereumjs-util

### PR DESCRIPTION
**Pull request by gre**

### CODE REVIEW

**Comment by holgerd77** [comment]
All tests are failing on this. This requires deeper work on the library, not just updating the dependencies.

**Comment by gre** [comment]
mmh. weirdly I was able to pass tests in local.

```
MacBook-Pro-de-Gaetan:ethereumjs-abi gre$ yarn list ethereumjs-util
yarn list v1.3.2
warning Filtering by arguments is deprecated. Please use the pattern option instead.
└─ ethereumjs-util@5.1.3
✨  Done in 0.35s.
MacBook-Pro-de-Gaetan:ethereumjs-abi gre$ yarn test
yarn run v1.3.2
$ istanbul test _mocha -- --reporter spec


  ✓ decoding address with leading 0
  official test vector 1 (encoding)
    ✓ should equal

  official test vector 3 (encoding)
    ✓ should equal

  official test vector 4 (encoding)
    ✓ should equal

  method signature
    ✓ should work with test()
    ✓ should work with test(uint)
    ✓ should work with test(uint256)
    ✓ should work with test(uint, uint)

  event signature
    ✓ should work with test()
    ✓ should work with test(uint)
    ✓ should work with test(uint256)
    ✓ should work with test(uint, uint)

  encoding negative int32
    ✓ should equal

  encoding negative int256
    ✓ should equal

  encoding string >32bytes
    ✓ should equal

  encoding uint32 response
    ✓ should equal

  encoding string response (unsupported)
    ✓ should equal

  encoding
    ✓ should work for uint256
    ✓ should work for uint
    ✓ should work for int256

  encoding bytes33
    ✓ should fail

  encoding uint0
    ✓ should fail

  encoding uint257
    ✓ should fail

  encoding int0
    ✓ should fail

  encoding int257
    ✓ should fail

  encoding uint[2] with [1,2,3]
    ✓ should fail

  encoding uint8 with 9bit data
    ✓ should fail

  decoding uint32
    ✓ should equal

  decoding uint256[]
    ✓ should equal

  decoding bytes
    ✓ should equal

  decoding string
    ✓ should equal

  decoding int32
    ✓ should equal
    ✓ should fail

  decoding bool, uint32
    ✓ should equal

  decoding bool, uint256[]
    ✓ should equal

  decoding uint256[], bool
    ✓ should equal

  decoding fixed-array
    ✓ uint[3]

  decoding (uint[2], uint)
    ✓ should work

  stringify
    ✓ should be hex prefixed for address
    ✓ should be hex prefixed for bytes
    ✓ should be hex prefixed for bytesN
    ✓ should be a number for uint
    ✓ should be a number for uintN
    ✓ should be a number for int
    ✓ should be a number for intN
    ✓ should work for bool (true)
    ✓ should work for bool (false)
    ✓ should work for address[]
    ✓ should work for address[2]
    ✓ should work for bytes[]
    ✓ should work for bytes[2]
    ✓ should work for uint[]
    ✓ should work for uint[3]
    ✓ should work for int[]
    ✓ should work for int[3]
    ✓ should work for multiple entries

  solidity tight packing bool
    ✓ should equal

  solidity tight packing address
    ✓ should equal

  solidity tight packing string
    ✓ should equal

  solidity tight packing bytes
    ✓ should equal

  solidity tight packing bytes8
    ✓ should equal

  solidity tight packing uint
    ✓ should equal

  solidity tight packing uint16
    ✓ should equal

  solidity tight packing int
    ✓ should equal

  solidity tight packing int16
    ✓ should equal

  solidity tight packing multiple arguments
    ✓ should equal

  solidity tight packing sha3
    ✓ should equal

  solidity tight packing sha3 #2
    ✓ should equal

  solidity tight packing sha256
    ✓ should equal

  solidity tight packing ripemd160
    ✓ should equal

  solidity tight packing with small ints
    ✓ should equal

  converting from serpent types
    ✓ should equal

  converting to serpent types
    ✓ should equal

  utf8 handling
    ✓ should encode latin and extensions
    ✓ should encode non-latin characters
    ✓ should decode latin and extensions
    ✓ should decode non-latin characters

  encoding ufixed128x128
    ✓ should equal

  encoding fixed128x128
    ✓ should equal

  decoding ufixed128x128
    ✓ should equal
    ✓ decimals should fail

  decoding fixed128x128
    ✓ should equal
    ✓ decimals should fail

  encoding -1 as uint
    ✓ should throw

  encoding 256 bits as bytes
    ✓ should not leave trailing zeroes

  decoding (uint128[2][3], uint)
    ✓ should work

  decoding (uint128[2][3][2], uint)
    ✓ should work

  decoding (uint[3][], uint)
    ✓ should work

  decoding (uint[][3], uint)
    ✓ should work


  89 passing (48ms)

✨  Done in 0.58s.
```

**Comment by gre** [comment]
it looks like the error fails because ethereumjs-util is still not published in ES5 (fails on a `let` inside the travis node runtime). so maybe it was not correctly fixed in the util library ?

**Comment by holgerd77** [comment]
Ah no, of course, we have to wait unit ``ethereumjs-util`` ``v5.1.4`` has been published (still one review outstanding).

**Pull request merged**
