### PR TITLE
New release v0.6.8

### PR DESCRIPTION
**Pull request by holgerd77**
//cc @alex-forshtat-tbk @djrtwo

### CODE REVIEW

**Comment by alcuadrado** [comment]
I don't understand why this version is `0.7.0` instead of `0.6.8`. If we change the second number, people who have this dependency specified as `^0.6.x` won't get this update. I suspect that's the case for most users.

**Comment by holgerd77** [comment]
@alcuadrado I am following semantic versioning here https://semver.org/, which states for minor versions: "when you add functionality in a backwards compatible manner" - which is the case here - and leaves patch versions for bug fixes.

I came more and more to the conclusion over time that semantic versioning works best if one is just sticking to the definitions and do not the versioning - with some exceptions and blurry cases - after personal estimations ("this is a more important feature, it needs a major bump...").

Wouldn't insist though that this is the final version of wisdom for all particular cases. @s1na do you have got a somewhat stronger opinion here? Others?

I would just generally say, when having a standard it works best if people stick also to the parts they personally disagree to some extend, so that it generally becomes reliable and predictable for others what to expect.

**Comment by holgerd77** [comment]
Will leave this open for 1-2 days for discussion or comment before merge.

**Comment by alcuadrado** [comment]
I agree with adhering to semver, that's why I raised my concern, as major 0 is a special case in semver. 

Strictly speaking, it means that the package is completely unstable, as stated [here](https://semver.org/#spec-item-4). But the npm ecosystem gives it another meaning: if the major is 0, minor is used as major. This is discribed [here in the npm docs](https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004).

For example, this is how solidity manages its version numbers.

**Comment by holgerd77** [comment]
@alcuadrado ah, didn't know about this 0-version aspect of semver, up till now I treated all 0.x releases in the same way as 1.x, 2.x, and so on. 

Not sure how much we want to take this new/more correct semantics into account in the future on releases - don't have a strong opinion on this. We can very much release this release as `v0.6.8` though I would say, have pushed an updated version.

Will merge (CI is just - again - failing due to this temporary Coveralls outage) and then do the release.

**Comment by alcuadrado** [comment]
> @alcuadrado ah, didn't know about this 0-version aspect of semver, up till now I treated all 0.x releases in the same way as 1.x, 2.x, and so on.

It's really weird. I only learned about it because that's what solidity uses. 

> Not sure how much we want to take this new/more correct semantics into account in the future on releases - don't have a strong opinion on this.

I think avoiding major version bumps as much as it's reasonably possible is a good thing. There are lots of projects that are barely maintained in the Ethereum ecosystem, but that still have lots of direct or indirect users. Those projects won't receive any fix or update after a major version bump.

**Comment by holgerd77** [comment]
> I think avoiding major version bumps as much as it's reasonably possible is a good thing. There are lots of projects that are barely maintained in the Ethereum ecosystem, but that still have lots of direct or indirect users. Those projects won't receive any fix or update after a major version bump.

That's really a good point, didn't think about it from that angle yet.

**Pull request merged**
