### PR TITLE
Include fixed size array size in offset for dynamic type

### PR DESCRIPTION
**Pull request by yondonfu**
Currently, when ABI encoding arguments, the offset in bytes to the start of the data area for dynamic types does not take into account the size of fixed arrays since `headLength` is set to `32 * types.length` (https://github.com/ethereumjs/ethereumjs-abi/blob/master/lib/index.js#L340). This would treat any fixed size array arguments as only taking up 32 bytes when they should take up 32 * `size of array` bytes. According to the ABI specification, each element of a fixed size array should take up 32 bytes i.e.uint256[0] takes up 32 bytes and uint256[1] takes up 32 bytes`. 

This includes a fix for the offset calculation along with a test. I can add more tests if needed.

### CODE REVIEW

**Comment by Kuzirashi** [comment]
This is good. My transaction passes now on etherscan while on 0.6.5 release it was erroring with out of gas error all the time.

I have a method with fixed length array argument and this PR seems to fix the issue. Could you fix this so repo maintainer could merge it?

**Comment by Kuzirashi** [comment]
@axic @frozeman @yondonfu 

Seems like tests are failing because of Travis, so maybe we can just kick off them again? MyCrypto is relying on this library and we would really love if we manage to get this fix upstream. Thank you guys.

**Comment by holgerd77** [comment]
Hi @Kuzirashi, this is not failing because of Travis, but there is a linting (code-formatting) error in the code provided by @yondonfu:

```
/home/travis/build/ethereumjs/ethereumjs-abi/lib/index.js:342:25: Missing space before function parentheses.
```

So the following line has to be adopted like this to fit the code-formatting standards:

```
types.forEach(function(type) {
types.forEach(function (type) {
```

(this can also often be done by running the ``lint`` command with ``--fix`` parameter.

@yondonfu can you do this change? Then tests should pass through.

**Comment by yondonfu** [comment]
@holgerd77 Fixed the linting error. Coveralls seems to be complaining about a decrease in coverage though I'm not sure what the cause of the coverage decrease is as the additional code in `rawEncode` seems to be covered by the additional test case.

**Comment by holgerd77** [comment]
@yondonfu Thanks, cool! Coverage is no blocking issue, this is often a bit irritating, since with most PRs it is the case that coverage decreases a bit - if e.g. one new line is added but no test case, this is inevitable.

**Comment by holgerd77** [comment]
Released within [v0.6.6](https://github.com/ethereumjs/ethereumjs-abi/releases/tag/v0.6.6).

(Sorry, I know it tooke ages).

**Pull request merged**
