### PR TITLE
Allow using '0x...' as input value for bytes

### PR DESCRIPTION
**Pull request by yann300**

### CODE REVIEW

**Comment by axic** [comment]
I wonder if it would be better to instead require a `Buffer` for bytes and let the caller make the decision?

**Comment by yann300** [comment]
That would break project that already use it (Mist?) . But I am fine with it .. that is cleaner anyway

**Comment by yann300** [comment]
That's also very convenient to be able to input a hex string (specially when you have to deal with arrays...)
what do you want to do with this one? cause it leads to a very nasty bug in Remix...

**Comment by holgerd77** [comment]
@axic State of discussion in this PR is also unclear, needs further clarification.

**Pull request closed without merging**
